from interact import validator as vm

# 卫星网络创建相关命令的选择
SATELLITE_NETWORK_RELATED_QUESTION = [
    {
        "type": "list",
        "name": "command",
        "message": "What is the command of your constellation?",
        "choices": [
            "create",
            "stop",
            "remove",
            "continue",
            "inspect",
            "send"
        ]
    }
]

# 区块链创建相关命令的选择
CHAIN_MAKER_RELATED_QUESTION = [
    {
        "type": "list",
        "name": "command",
        "message": "What is the command of your created block chain?",
        "choices": [
            "create",
            "start",
            "stop",
            "remove",
            "send",
            "capture",
            "create_contract",
            "invoke_contract",
            "search_contract"
        ]
    }
]

# 区块链配置文件是否删除的选择
CHAIN_MAKER_CONFIG_DELETE_QUESTION = [
    {
        "type": "list",
        "name": "command",
        "message": "Whether to regenerate the configuration files generated by the chain?",
        "choices": [
            "yes",
            "no"
        ]
    }
]

# 询问用户是否需要继续卫星网络创建相关的程序
PROGRAM_CONTINUE_QUESTION = [
    {
        "type": "list",
        "name": "continue",
        "message": "Continue the program?",
        "choices": [
            "yes",
            "no"
        ]
    }
]

# 询问用户消息的类型
COMMAND_TYPE_QUESTION = [
    {
        "type": "list",
        "name": "command_type",
        "message": "Which type of message you want to send to?",
        "choices": [
            "normal",
            "length",
            "bloom"
        ]
    }
]

# 询问用户向哪个卫星发送消息, 以及发送的消息
NODE_SELECTION_QUESTION = [
    {
        "type": "list",
        "name": "node",
        "message": "Which node you want to send message to?",
        "choices": [
        ],
    },
]

# 询问用户关于布隆过滤器的设置
BLOOM_FILTER_SETTINGS = [
    {
        "type": "input",
        "name": "bloom_filter_length",
        "message": "What is the size of bloom filter?",
        "default": "32"
    },
    {
        "type": "input",
        "name": "hash_seed",
        "message": "What is the hash seed of bloom filter?",
        "default": "18"
    },
    {
        "type": "input",
        "name": "number_of_hash_funcs",
        "message": "What is the number of hash functions of bloom filter?",
        "default": "5"
    }
]

# 询问日志监听记录器的问题
KERNEL_LOG_READER_QUESTION = [
    {
        "type": "input",
        "name": "kernel_log_file_path",
        "message": "What's the path of the kernel log file?",
        "default": "/var/log/kern.log"
    },
    {
        "type": "list",
        "name": "remove_or_retain",
        "message": "Do you want to remove or retain the kernel log file?",
        "choices": [
            "Remove",
            "Retain"
        ]
    }, {
        "type": "input",
        "name": "kernel_log_pre_msg",
        "message": "What's the log pre msg of the kernel log file?",
        "default": "[zeusnet's kernel info]:"
    }, {
        "type": "input",
        "name": "interval",
        "message": "What's the modification check interval?",
        "default": "1",
        "validate": vm.FloatValidator
    }
]

# 获取 prepare.sh 的参数
GET_PARAMETERS_OF_PREPARE_SH = [
    {
        "type": "input",
        "name": "node_count",
        "message": "What's the node count of this configuration?",
        'default': "4",
        "validate": vm.IntegerValidator
    },
    {
        "type": "input",
        "name": "p2p_port",
        "message": "What's the start p2p port of each node?",
        "default": "11301",
        "validate": vm.IntegerValidator
    },
    {
        "type": "input",
        "name": "rpc_port",
        "message": "What's the start rpc port of each node?",
        "default": "12301",
        "validate": vm.IntegerValidator
    }
]

# udp 视频客户端的问题
