import math

# GEO Config
R_EARTH = 6371000
POLAR_REGION_LATITUDE = 66.5 / 180 * math.pi
LIGHT_SPEED_M_S = 3e8

ALTITUDE_KEY = 0
LONGITUDE_KEY = 1
LATITUDE_KEY = 2

SATELLITE_NODE_PREFIX = "sat"
GROUND_STATION_PREFIX = "gnd"
CONSENSUS_NODE_PREFIX = "consensus_node"


